# Generated by Django 3.2.10 on 2021-12-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maize',
            fields=[
                ('maize_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('seasonal_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='seasonal price(UGX)')),
                ('production', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='production(KGs)')),
            ],
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preciptation_rate', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='precipitation rate(mm)')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('unique_id', models.CharField(help_text='Enter your identification number', max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('telephone', models.IntegerField(help_text='Enter 10 digit phone number')),
                ('region', models.CharField(help_text='Enter region you grow maize', max_length=50)),
                ('maize', models.ManyToManyField(help_text='Enter maize type', to='api.Maize')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
