# Generated by Django 3.2.10 on 2022-01-14 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('production', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precipitation', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Maize',
            fields=[
                ('maize_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('seasonal_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='seasonal price(UGX)')),
                ('production', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='production(KGs)')),
            ],
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preciptation_rate', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='precipitation rate(mm)')),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Enter username', max_length=50)),
                ('region', models.CharField(help_text='Enter region', max_length=50)),
                ('month', models.CharField(help_text='Enter month', max_length=50)),
                ('production', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('unique_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(default='johndoe', help_text='Enter user_name', max_length=100)),
                ('email', models.EmailField(default='test@example.com', help_text='enter your email address', max_length=254, unique=True)),
                ('first_name', models.CharField(default='John', help_text='Enter first name', max_length=100)),
                ('last_name', models.CharField(default='Doe', help_text='Enter last name', max_length=100)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('telephone', models.IntegerField(help_text='Enter 10 digit phone number')),
                ('region', models.CharField(help_text='Enter region you grow maize', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, related_name='FarmerGroups', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BFarmersUsers', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='FarmerUserPermissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
