# Generated by Django 3.2.10 on 2021-12-20 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='FarmerGroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='FarmerUserPermissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
