# Generated by Django 3.2.10 on 2022-01-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='precipitation',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='production',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
