# Generated by Django 3.2.10 on 2021-12-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211208_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='telephone',
            field=models.IntegerField(help_text='Enter 10 digit phone number'),
        ),
    ]
